# Generated by Django 5.0.1 on 2024-02-09 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NextQuestionLogic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_to_the_prev_question', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.choice')),
                ('default_next_question', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_next_question', to='app.question')),
                ('next_question', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_question', to='app.question')),
                ('prev_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prev_question', to='app.question')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='app.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.survey'),
        ),
    ]
