# Generated by Django 5.0.1 on 2024-02-09 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextquestionlogic',
            name='choice_to_the_prev_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.choice'),
        ),
        migrations.AlterField(
            model_name='nextquestionlogic',
            name='default_next_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_next_question', to='app.question'),
        ),
        migrations.AlterField(
            model_name='nextquestionlogic',
            name='next_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_question', to='app.question'),
        ),
    ]
