# Generated by Django 5.0.1 on 2024-02-13 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_surveyresults'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyresults',
            old_name='choice_id',
            new_name='choice',
        ),
        migrations.RenameField(
            model_name='surveyresults',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='surveyresults',
            old_name='survey_id',
            new_name='survey',
        ),
        migrations.RenameField(
            model_name='surveyresults',
            old_name='user_id',
            new_name='user',
        ),
    ]
