# Generated by Django 5.0.1 on 2024-02-13 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_choice_id_surveyresults_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresults',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.choice'),
        ),
    ]
